import random

counties = [
    "Bedfordshire",
    "Berkshire",
    "Bristol",
    "Buckinghamshire",
    "Cambridgeshire",
    "Cheshire",
    "City of London",
    "Cornwall",
    "County Durham",
    "Cumbria",
    "Derbyshire",
    "Devon",
    "Dorset",
    "East Riding of Yorkshire",
    "East Sussex",
    "Essex",
    "Gloucestershire",
    "Middlesex",
    "Greater Manchester",
    "Hampshire",
    "Herefordshire",
    "Hertfordshire",
    "Isle of Wight",
    "Kent",
    "Lancashire",
    "Leicestershire",
    "Lincolnshire",
    "Merseyside",
    "Norfolk",
    "North Yorkshire",
    "Northamptonshire",
    "Northumberland",
    "Nottinghamshire",
    "Oxfordshire",
    "Rutland",
    "Shropshire",
    "Somerset",
    "South Yorkshire",
    "Staffordshire",
    "Suffolk",
    "Surrey",
    "Tyne and Wear",
    "Warwickshire",
    "West Midlands",
    "West Sussex",
    "West Yorkshire",
    "Wiltshire",
    "Worcestershire",
    "Aberdeenshire",
    "Angus",
    "Argyll and Bute",
    "Clackmannanshire",
    "Dumfries and Galloway",
    "Dundee City",
    "East Ayrshire",
    "East Dunbartonshire",
    "East Lothian",
    "East Renfrewshire",
    "West Lothian",
    "Falkirk",
    "Fife",
    "Strathclyde",
    "Highland",
    "Inverclyde",
    "Tayside",
    "North Lanarkshire",
]

towns = [
    "Bedford",
    "Luton",
    "Reading",
    "Slough",
    "Bristol",
    "Buckingham",
    "Cambridge",
    "Chester",
    "City of London",
    "Truro",
    "Durham",
    "Carlisle",
    "Derby",
    "Exeter",
    "Poole",
    "Hull",
    "Brighton",
    "Chelmsford",
    "Gloucester",
    "Manchester",
    "Southampton",
    "Hereford",
    "St Albans",
    "Isle of Wight",
    "Maidstone",
    "Lancaster",
    "Leicester",
    "Lincoln",
    "Liverpool",
    "Norwich",
    "York",
    "Northampton",
    "Newcastle",
    "Nottingham",
    "Oxford",
    "Rutland",
    "Shrewsbury",
    "Taunton",
    "Sheffield",
    "Stafford",
    "Ipswich",
    "Guildford",
    "Newcastle upon Tyne",
    "Warwick",
    "Birmingham",
    "Chichester",
    "Bradford",
    "Wolverhampton",
    "Chesterfield",
    "Worcester",
    "Aberdeen",
    "Dundee",
    "Dumfries",
    "Kirkcaldy",
    "Glasgow",
    "Inverness",
    "Greenock",
]

transit = ['Flight', 'Taxi', 'Train', 'Bus', 'Coach', 'Tube', 'Gondola', 'Ship']
places = ['London', 'Paris', 'New York', 'Tokyo', 'Sydney', 'Berlin', 'Moscow'] + ['Rome', 'Madrid', 'Dubai', 'Singapore', 'Hong Kong', 'Los Angeles']
couriers = ["Mobile", "Pick-up at Station", "Postage", "Fax", "Carrier Pigeon"]

def statuses(rows):
    statuses = ["active"] * int(0.6 * rows) + ["archived"] * int(0.2 * rows) + ["suspended"] * int(0.2 * rows)
    random.shuffle(statuses)
    return statuses

domains = ['org', 'com', 'net', 'co.uk', 'gov']
emails = ['gmail', 'yahoo', 'yandex', 'hotmail', 'outlook']